name: xeus-r-kernel
channels:
  - https://prefix.dev/emscripten-forge-dev
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-r
  - r-ggplot2
  - r-archdata
  - r-rcurl
  - r-jsonlite
  - r-dbi
  - r-rsqlite
  - r-sparql
  - r-dplyr
  - r-miniui
  - r-rjava
  - r-tabulizer
  # - devtools::install_github("daniel1noble/metaDigitise")